apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mysql-database: c29mdHRlaw== # defaultdb en base64
  mysql-user: bmljb211cm9z # avnadmin en base64
  mysql-password: cGFzc3dvcmQ= # password en base64
  mysql-root-password: cGFzc3dvcmQ= # password en base64
