apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  mysql-database: c29mdHRlaw== # softtek en base64
  mysql-user: bXVyb3M= # muros en base64
  mysql-password: cGFzc3dvcmQ= # password en base64
  mysql-root-password: cGFzc3dvcmQ= # password en base64
